Bratsun
NikolaySavenko/bignum-wizard pull request #61
Opened 2021-04-01 09:37 UTC by m0m0sha

Add N12

2021-04-01 19:41 UTC, NikolaySavenko requested changes
fix all errors and warnings

2021-04-01 19:42 UTC, NikolaySavenko commented
Add project

2021-04-01 22:39 UTC, Nestea-tea13 requested changes
Исправить пример с отрицательным числом, так как это тест для модуля натуральных чисел и добавить тесты с 0 в каждой позиции

2021-04-02 12:43 UTC, NikolaySavenko commented
ADD PROJECT

2021-04-02 17:02 UTC, closed without merging