Test for Q2
NikolaySavenko/bignum-wizard pull request #62
Opened 2021-04-01 14:04 UTC by VetaSolo

Test for Q2

2021-04-01 19:38 UTC, NikolaySavenko approved these changes, later dismissed

2021-04-01 22:41 UTC, Nestea-tea13 requested changes
Так как первое число должно быть целым, добавить тесты с отрицательными значениями и 0, а так же добавить примеры где знаменатель тоже длинное число

2021-04-02 11:00 UTC, NikolaySavenko approved these changes

2021-04-02 17:02 UTC, Nestea-tea13 approved these changes
Q2 good

2021-04-02 17:02 UTC, merged