Add N9
NikolaySavenko/bignum-wizard pull request #9
Opened 2021-03-24 16:35 UTC by VetaSolo

будет несоответсвие типов из-за того что в N6 int (умножение еще не добавленно)

2021-03-24 17:50 UTC, NikolaySavenko requested changes
Compiler Error CS0161
https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0161

2021-03-24 17:51 UTC, Nestea-tea13 approved these changes, later dismissed
N9 good

2021-03-24 17:53 UTC, NikolaySavenko requested changes
add class name before method usage
COM_NN_D -> Natural1_5.COM_NN_D

2021-03-26 15:32 UTC, NikolaySavenko approved these changes

2021-03-26 15:36 UTC, Nestea-tea13 approved these changes
N-9 work

2021-03-26 15:36 UTC, merged